### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [koharubiyori/Moegirl-plus-native#1]
请问是否可以将应用发布到 F-Droid？

**Comment by koharubiyori** [comment]
抱歉，尝试了一下搭建F-Droid发布环境但失败了，由于不想在这上面花费太长时间，暂时作罢。

**Comment by linsui** [comment]
我可以负责打包提交，F-Droid 的构建环境还挺麻烦的，不过可以直接用 F-Droid 的 CI。谢谢！

**Comment by koharubiyori** [comment]
那麻烦你了，可以提供一下你的邮箱吗，我把[/app/build.gradle#L9](https://github.com/koharubiyori/Moegirl-plus-native/blob/ff6c5a6927bcfae48df8c52993be1fdf43e00834/app/build.gradle#L9)引用的`key.properties`文件发给你

**Comment by linsui** [comment]
F-Droid 使用自己的密钥签名应用，构建元数据中构建的是未签名的 apk。

**Comment by koharubiyori** [comment]
了解了，那还需要我做什么吗

**Comment by linsui** [comment]
我稍后会在 F-Droid 那边开一个 MR 提交构建元数据，然后在这边开一个 MR 添加 fastlane 元数据。请问 H 萌娘的 flavor 也可以一起发布吗？我刚刚注意到。另外 2.3.3 的 tag 打在 2.3.2 的提交上了。不过问题不大。

**Comment by koharubiyori** [comment]
H萌娘的版本还不行，tag打错的问题我刚刚又重发了一次

**Comment by linsui** [comment]
已在 F-Droid 那边开了一个 [MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10544)，这边也提交了一个 PR。麻烦你检查一下有没有什么需要修改的。谢谢！

**Comment by linsui** [comment]
我去掉了启动时检查更新，因为 F-Droid 的版本和 GitHub 的版本签名不一致。如果没有问题就可以合并了。

**Comment by koharubiyori** [comment]
> 我去掉了启动时检查更新
请问这里是指在你的本地(或是其他地方fork的仓库？我不是很了解F-Droid的发布机制)进行的修改，还是说要提一个PR到这里？无论哪一种感觉都不是很好，我下版本会再加一个flavor用来区分是否是要上传到F-Droid的版本，如果是则禁用启动时检查更新，到时候麻烦你再改一下F-Droid的发布配置吧

**Comment by linsui** [comment]
是在 F-Droid 的构建元数据中。https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10544/diffs#4291f3a7c0e2a6a852516a2ef17bd74567643c4a_0_31 

> 无论哪一种感觉都不是很好，我下版本会再加一个flavor用来区分是否是要上传到F-Droid的版本，如果是则禁用启动时检查更新，到时候麻烦你再改一下F-Droid的发布配置吧

谢谢！那么是现在合并还是等到下一个版本发布在合并？

**Comment by koharubiyori** [comment]
现在合并吧

**Comment by linsui** [comment]
已合并，大概两到三天会进入 F-Droid 的存储库。F-Droid 的徽标

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.moegirlviewer)

```
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.moegirlviewer)
```

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10606 更新 moegirl flavor。

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10607 打包 hmoe flavor。

**Comment by koharubiyori** [comment]
感谢！

**Comment by linsui** [comment]
已合并，两三天后会进入存储库 https://f-droid.org/packages/koharubiyori.hmoegirl。感谢你的帮助和支持！
