### ISSUE TITLE
解析失败

### ISSUE THREAD

**Issue by leo-JN** [koharubiyori/Moegirl-plus-native#10]
安装包无法解析 
安卓版本:7.1.1
系统版本:amigo os 4.0.6s.7
现象:
![20220324-030733](https://user-images.githubusercontent.com/102203963/159777298-6f874cc7-6d6e-4963-a86e-2ae90199e879.png)

>

**Comment by 850710247liu** [comment]
> 安装包无法解析 
> 安卓版本:7.1.1
> 系统版本:amigo os 4.0.6s.7
> 现象:
> ![20220324-030733](https://user-images.githubusercontent.com/102203963/159777298-6f874cc7-6d6e-4963-a86e-2ae90199e879.png)
> 
> > 

很遗憾 客户端不再适配安卓7.0了 需要7.0以上版本

**Comment by koharubiyori** [comment]
最新的2.5.0版本已经向下适配至安卓6。
