### ISSUE TITLE
请求上架到App Center

### ISSUE THREAD

**Issue by 850710247liu** [koharubiyori/Moegirl-plus-native#12]
只需要github登录后就可选库上架，中国大陆可访问，且该商店界面用户使用更方便
https://install.appcenter.ms/apps

**Comment by koharubiyori** [comment]
App Center不支持多个flavor的app，根据[这里](https://github.com/microsoft/appcenter/issues/32)，已经过去3年这个常用的特性还没支持，看评论微软好像已经摆烂App Center了，说不再开发新功能。
